name: Secure DevSecOps CI (OIDC)

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    # -----------------------------
    # Checkout Code
    # -----------------------------
    - name: Checkout code
      uses: actions/checkout@v3

    # -----------------------------
    # Secret Scanning
    # -----------------------------
    - name: Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2

    # -----------------------------
    # File System Scan
    # -----------------------------
    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        exit-code: 1

    # -----------------------------
    # Configure AWS (OIDC)
    # -----------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::528757804354:role/github-actions-devops-role
        aws-region: ap-south-1

    # -----------------------------
    # Login to ECR
    # -----------------------------
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # -----------------------------
    # Build Docker Image
    # -----------------------------
    - name: Build Docker Image
      run: docker build -t app ./app

    # -----------------------------
    # Scan Docker Image
    # -----------------------------
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: app
        exit-code: 1

    # -----------------------------
    # Tag Docker Image (SHA + latest)
    # -----------------------------
    - name: Tag Docker Image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker tag app:latest ${{ steps.login-ecr.outputs.registry }}/secure-devops-app:$IMAGE_TAG
        docker tag app:latest ${{ steps.login-ecr.outputs.registry }}/secure-devops-app:latest

    # -----------------------------
    # Push Docker Image
    # -----------------------------
    - name: Push Docker Image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/secure-devops-app:$IMAGE_TAG
        docker push ${{ steps.login-ecr.outputs.registry }}/secure-devops-app:latest